### ISSUE TITLE
cordova-plugin-alipay\src\android\libs\alipaySingle-20160825.jar" not found!

### ISSUE THREAD

**Issue by Arcko** [joshualzb/cordova-plugin-alipay#1]
C:\Users\Arcko\DLCPay>cordova platform add android
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: io.cordova.hellocordova
        Name: HelloCordova
        Activity: MainActivity
        Android target: android-23
Android project created with cordova-android@5.2.2
Installing "cordova-plugin-alipay" for android
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-alipay':CordovaError: Uh oh!
"C:\Users\Arcko\DLCPay\plugins\cordova-plugin-alipay\src\android\libs\alipaySingle-20160825.jar" not found!
    at copyFile (C:\Users\Arcko\DLCPay\platforms\android\cordova\lib\pluginHandlers.js:202:36)
    at copyNewFile (C:\Users\Arcko\DLCPay\platforms\android\cordova\lib\pluginHandlers.js:234:5)
    at handlers.source-file.install (C:\Users\Arcko\DLCPay\platforms\android\cordova\lib\pluginHandlers.js:37:17)
    at Object.ActionStack.process (C:\Users\Arcko\DLCPay\platforms\android\cordova\node_modules\cordova-common\src\ActionStack.js:56:25)
    at PluginManager.doOperation (C:\Users\Arcko\DLCPay\platforms\android\cordova\node_modules\cordova-common\src\PluginManager.js:117:20)
    at PluginManager.addPlugin (C:\Users\Arcko\DLCPay\platforms\android\cordova\node_modules\cordova-common\src\PluginManager.js:147:17)
    at Api.addPlugin (C:\Users\Arcko\DLCPay\platforms\android\cordova\Api.js:198:10)
    at handleInstall (C:\Users\Arcko\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:611:6)
    at C:\Users\Arcko\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:407:28
    at _fulfilled (C:\Users\Arcko\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
Error: Uh oh!
"C:\Users\Arcko\DLCPay\plugins\cordova-plugin-alipay\src\android\libs\alipaySingle-20160825.jar" not found!

**Comment by joshualzb** [comment]
alipaySingle-20160825.jar 去蚂蚁支付宝下载最新的sdk，里面有这个jar包，然后在config.xml里面配置一下文件映射就好了

**Comment by joshualzb** [comment]
我已经把jar包传上来了。
